import Image from "next/image";
import './project.css';
import lunaimg from '../../assets/lunaid.png'

export default function content(){
    return(
        <div class="magazine-layout">
            <div class="image-container">
                <Image src={lunaimg} alt="project1img" class="imgid" width={250} height={250}/>
            </div>
        <div class="text-container">
            <h1 class="magazine-title">NEAR AI</h1>
            <p class="magazine-description">NEAR AI is a collection of anime-style NFTs generated by AI using Generate Trait and published on the NEAR network. Each character in this collection is unique and designed to be used as a Profile Picture (PFP).</p>
        </div>
    </div>
    )
}